version: '2.1'
services:
  hello-mysql:
    container_name: iqmsoft-mysql
    image: 'mysql/mysql-server:5.7'
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: iqmsoft
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3301:3306'
    restart: always
  hello-app:
    image: iqmsoft-spring-boot-app
    build:
      context: ./springbootmysql
      dockerfile: Dockerfile
    ports:
      - '8087:8080'
    volumes:
      - /data/iqmsoft-spring-boot-app
    depends_on:
      hello-mysql:
        condition: service_healthy

